version: '3.1'
services:
  papercut:
      build: .
      restart: always
      depends_on:
        - mysql
      links:
        - mysql:database
      ports:
        - 9191:9191
        - 9192:9192
        - 9193:9193
      volumes:
        - papercut_logs:/papercut/server/logs
        - papercut_data:/papercut/server/data
      environment:
        PAPERCUT_ADMIN_USERNAME: admin
        PAPERCUT_ADMIN_PASSWORD: admin
        PAPERCUT_DATABASE_TYPE: MySQL
        PAPERCUT_DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
        PAPERCUT_DATABASE_USERNAME: papercut
        PAPERCUT_DATABASE_PASSWORD: papercut
        PAPERCUT_DATABASE_URL: jdbc:mysql://database/papercut
  mysql:
      image: mysql:5.7
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: papercut 
        MYSQL_DATABASE: papercut 
        MYSQL_USER: papercut 
        MYSQL_PASSWORD: papercut
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      depends_on:
          - mysql
      ports:
          - 8080:80
      environment:
          MYSQL_ROOT_PASSWORD: papercut
          PMA_HOST: mysql
volumes:
  papercut_logs:
  papercut_data:
