version: '3.1'

services:
  papercut:
    build: .
    restart: always
    platform: linux/x86_64
    depends_on:
      - mysql
    ports:
      - "9191:9191"
      - "9192:9192"
      - "9193:9193"
      - "631:631" # Exposing CUPS web interface
    volumes:
      - ~/.papercut/logs:/papercut/server/logs
      - ~/.papercut/conf:/papercut/server/data/conf
      - ~/.papercut/custom:/papercut/server/custom
      - ~/.papercut/backups:/papercut/server/data/backups
      - ~/.papercut/papercut/archive:/papercut/server/data/archive
      - ~/.papercut/cups-config:/etc/cups # Map CUPS configuration directory to host
    environment:
      PAPERCUT_ADMIN_USERNAME: admin
      PAPERCUT_ADMIN_PASSWORD: admin
      PAPERCUT_DATABASE_TYPE: MySQL
      PAPERCUT_DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
      PAPERCUT_DATABASE_USERNAME: papercut
      PAPERCUT_DATABASE_PASSWORD: papercut
      PAPERCUT_DATABASE_URL: jdbc:mysql://database:3306/papercut?useSSL=false
      PUID: 1001
      PGID: 1001


  mysql:
    image: mysql:5.7.42
    restart: always
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - ~/.papercut/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: papercut
      MYSQL_USER: papercut
      MYSQL_PASSWORD: papercut
      PUID: 1001
      PGID: 1001

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    depends_on:
      - mysql
    ports:
      - "7070:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
      PUID: 1001
      PGID: 1001
